montsuqi/monsiaj

build.xml
tsaurlの追加。署名する場合は、propertiesに以下を追加してください。
tsa=http://timestamp.globalsign.com/scripts/timstamp.dll
=> （古い）jarsignerを呼ぶ方式の削除

src/main/java/org/montsuqi/monsiaj/client/OpenIdConnect.java
IPへのログイン要求リクエストにいったんリダイレクトが挟まれるとのことなので、その対応です。
リダイレクトの部分だけ `setInstanceFollowRedirects(true);` で対応しようかと思いましたが、リクエストヘッダの Accept が保存されなかったので単に再度requestを実行する形にしています。
=> IPへのログイン要求リクエストのリダイレクト対応

src/main/java/org/montsuqi/monsiaj/client/ConfigPanel.java
LookAndFeel変更時にランチャーダイアログのLAFをその場で変更しないようにした。
(サーバ接続後の画面にはLAFが適用される。)
=> macOSでランチャーでLookAndFeelを変更した場合にnull pointer exceptionが発生しうまく動作しない場合があった。

src/main/java/org/montsuqi/monsiaj/client/Protocol.java
オンプレでの接続でGetBLOB、PostBLOBにAuthヘッダがついていなかった。
=> オンプレでクライアント保存で401 Unauthorizedになるのを修正

pom.xml
githubのアラートがでていたので2.0.12から2.0.15にアップデート。
ついでにmonsiajのバージョンも2.0.16に変更。
=> org.apache.pdfboxのセキュリティアップデート

src/main/java/org/montsuqi/monsiaj/client/Client.java, src/main/java/org/montsuqi/monsiaj/client/Protocol.java
ginbeeではJSONRPC get_messageを実行しないよう修正した。
get_messageはVPN回線のkeep-alive用に使用していたが、現在はwebsocketでkeep-aliveしているので不要
=> ginbeeではJSONRPC get_messageを呼ばないよう修正

src/main/java/org/montsuqi/monsiaj/client/ConfigPanel.java, src/main/java/org/montsuqi/monsiaj/client/Launcher.java
launch()でswing componentを使う前にLAF設定を行うようにした。
(constructorのinitLookAndFeel()で行うように)
=> ランチャーでSystemLookAndFeelにならないのを修正

pom.xml, src/main/java/org/montsuqi/monsiaj/client/ConfigPanel.java
Java 11の環境では問題ないがJava 8の環境ではString.strip()でエラーが発生しうまく動作しなかった。
String.strip()はJava 11からサポートのため、String.strip()はString.trim()のUnicode強化版とのことなので、今回除外したいのはASCIIの改行コードと空白なのでtrim()でも問題ない。
参考
https://codeday.me/jp/qa/20190309/383626.html
=> Java 8で動作するようString.strip()をString.trim()に変更

src/main/java/org/montsuqi/monsiaj/widgets/PandaHTML.java
日レセシステム管理の設定でクライアント接続時のマスターメニュー下部に任意のURLのWebページを表示する機能がある(PandaHTMLウィジェット)。
SSLクライアント認証を有効にして、URLにhttpsのページを指定した場合、SSLタブのCA証明書ファイルにURLのCA証明書が通常含まれないのでPandaHTML内でセキュリティエラーとなりエラーダイアログがでてクライアントが終了する。
マスターメニューのURL設定はマスターメニューの先にあるため、一度エラーとなるhttpsを設定してしまうと日レセクライアントからでは変更できくなる。
PandaHTMLでのセキュリティエラーを無視できればいいのだが単純にtry catchでくくっただけでは駄目だった。
ひとまずPandaHTMLの動作を無効にするシステムプロパティを追加する。
(glcient2にも同様の環境変数がある。)
=> システムプロパティにmonsia.disable.panda_htmlを追加

src/main/java/org/montsuqi/monsiaj/client/SSLSocketFactoryHelper.java
#193 の関連修正
SSLContext.setDefaultは不要だった。かつSSLクライアント認証のCA証明書のみをストアに設定し、市販の証明書を使ったhttpsユーザページ表示時にサーバ証明書エラーを誘発する。
当初、HttpURLConnectionのDefaultにSSLSocketFactoryを設定していたので必要だったかもしれないが、最近の修正でHttpURLConnectionのインスタンスに個別にSSLSocketFactoryを設定するようになったのでもう不要になった。
=> 不要なSSLContext.setDefaultの削除

src/main/java/org/montsuqi/monsiaj/client/Protocol.java
* monsiajプロキシ仕様
* 現行仕様
* 日レセ操作用のJSONRPCのHTTPクライアントにはNO_PROXY=*を設定しプロキシ利用できないように設定
* VPNの場合にお知らせページ https://www.orca.med.or.jp/info/ を表示するのにプロキシ設定が必要だがプロキシ設定するとプロキシ経由で日レセサーバに接続することになり日レセサーバに接続できない場合があるため
* WAF(TLS1.2のみのインターネット接続)の場合、VPNではないので基本プロキシ設定はいらないが、クライアント側の都合でプロキシを経由する場合、前述のNO_PROXY設定のため日レセサーバにアクセスできない
* -> NO_PROXY設定を単純に解除すると現行のVPNユーザが日レセサーバに接続できない可能性がある
* 修正案
* AUTH_URIがsms-*.orca.orcamo.jpの場合のみJSONRPC HTTPクライアントにNO_PROXYを設定する
=> VPN経由(sms-*.orca.orcamo.jp)のときのみNO_PROXYを設定するよう変更

src/main/java/org/montsuqi/monsiaj/client/Protocol.java
オンプレのglserverが認証エラーをHTTP403で返していたので両方設定していたが、glserverを修正したのでわけるようにした。
=> HTTP 401認証エラーとHTTP 403の処理を分離した。

pom.xml, src/main/java/org/montsuqi/monsiaj/util/LogFile.java, src/main/java/org/montsuqi/monsiaj/util/TempFile.java, src/main/resources/log4j2.xml
ctimeの経過時間で削除するためのしきい値が即値計算の際にint型となりオーバーフローし負値となっていた。
そのため作成直後のログファイルも削除されログが書き込まれない状態となった。
=> ログファイル削除が常に実行される

src/main/java/org/montsuqi/monsiaj/client/OpenIdConnect.java, src/main/java/org/montsuqi/monsiaj/client/Protocol.java
protocol.getHttpURLConnection(uri)を使うよう修正。
* 通常認証、SSO認証ができることを確認
=> #194の影響でSSO接続できなくなっていた

pom.xml, src/main/java/org/montsuqi/monsiaj/client/Protocol.java, src/main/java/org/montsuqi/monsiaj/client/PushReceiver.java, src/main/java/org/montsuqi/monsiaj/client/SSLSocketFactoryHelper.java
see #204
調べたところ org.eclipse.jetty.websocket はプロキシに対応していなかったので、tyrus-standalone-clientに変更した。
* プロキシなしでWebSocket接続、PUSH通知受信が可能なこと(wss + SSLクライアント認証)
* プロキシ経由でWebSocket接続、PUSH通知受信が可能なこと(wss + SSLクライアント認証)
* WebSocketサーバ切断時に再接続が可能なこと
* 定期的なPingフレーム送信によるTCP切断検知と再接続
* GAM(Soft VPN)を起動したまま、LANケーブル抜き差しを行ない、Pingによる死活監視、VPN復帰後の再接続が動作することを確認した。
* ベーシック認証を設定しないようにした
* 日レセクラウドのWebSocketサーバで認証しないようになったため
=> fix-204 WebSocket接続のプロキシ対応

pom.xml, src/main/java/org/montsuqi/monsiaj/client/Launcher.java, src/main/java/org/montsuqi/monsiaj/loader/Loader.java
* 日レセ有償化に伴い、monsiajの配布元をベーシック認証がかかったhttpsサーバに移動する
* https://dl.orca.med.or.jp
* ベーシック認証がかかっているためユーザ、パスワード(医療機関ID、アクセスキー)を入力してもらう必要がある
* 動作自体は有償化対応以前の動きをほぼ踏襲
* サーバに最新版バージョンを問い合わせ、手元のバージョンと差異があればダウンロードしてキャッシュ保存
* キャッシュから起動
* デフォルトのバージョン取得URLとパッケージ取得URLが変わるので設定ファイルをloader.propertiesからloader2.propertiesに変更して初期化して作り直す
* 最新バージョン問い合わせ時にユーザ、パスワードを設定ファイルまたはダイアログから取得して認証設定する
* 最初に設定ファイルを読込、ID、アクセスキーがあればそれを設定して接続、失敗もしくは設定がない場合はダイアログを表示して入力を促す
* あわせて5回認証失敗したら終了する
* 認証に成功し、ダイアログの「アクセスキーを保存」にチェックがある場合に設定ファイルにID、アクセスキーを保存する
* 正しいID、アクセスキーを入力した場合に最新版ダウンロードして起動すること
* アクセスキーを保存にチェックした場合、次回起動からはダイアログ表示なしで最新版チェック&起動が動作すること
* アクセスキーを保存にチェックしなかった場合、再度ダイアログが表示されること
* 誤ったID、アクセスキーを入力した場合、5回目もしくは4回目まではダイアログ表示され、それでも失敗すると規定回数到達エラーが表示されること
* アクセスキーを平文保存しているのを対策する
* [簡易対応]固定鍵で共通鍵暗号する
* …
=> 自動更新版(monsiaj-loader-x.x.x.jar)の有償化対応

pom.xml, src/main/java/org/montsuqi/monsiaj/client/PushReceiver.java
一度回線が切れると30秒毎に切断と再接続を繰り返す。
ExecutorServiceによる10秒間隔のPingの送信処理の挿入位置が悪かったため、初回接続時のみPing送信が有効で、再接続した後はおそらく古い切断済みのSessionでPingを送信するためにMaxIdleTimeout=30sとなりonClose処理が走っていたと考えられる。
onOpenでExecutorServiceを登録実行する、onCloseでExecutorServiceを停止するよう修正した。
* GAM(SoftwareVPN)とWAF(TLS1.2、インターネット接続)のそれぞれで意図的に回線切断し、再接続を行ない、PingPong通信が動作すること、切断、再接続を繰り返さないことを確認した。
=> WebSocket再接続後のPingがうまく動作せず回線の無通信時間制限にかかり再接続を繰り返す不具合

src/main/java/org/montsuqi/monsiaj/client/CertificateManager.java, src/main/java/org/montsuqi/monsiaj/client/Client.java
* サーバURLで証明書更新API(共通基盤)のホストを変更するよう修正
* WAFのPOSTメソッドの制限のために、POSTの場合にダミーBodyを設定
* 証明書更新に失敗してもエラーで終了とせずにクライアント接続を行なう
=> 証明書自動更新機能修正

pom.xml, src/main/java/org/montsuqi/monsiaj/util/PDFPrint.java
* 一般サイズでない場合に mediaSizeName = null を指定していたのが問題だった
* mediaSizeNameを指定しなければ適切に印刷してくれる(プリンタによるかもだが
* PDFライブラリpdfboxへの切替時に入ったバグ(用紙サイズ指定部分を以前の実装と同等に戻した)
=> ラベルプリンタ用紙など一般的でない用紙の印刷ができなかった

src/main/java/org/montsuqi/monsiaj/client/ConfigPanel.java
* linux環境でチェックボックス右空白部分が反応しないのを確認
* サーバ接続に問題ないことを確認
=> ランチャーのチェックボックスの右空白部分でも反応してしまう動作を修正

src/main/java/org/montsuqi/monsiaj/client/CertificateManager.java
* #215 の対応
* ubuntuで証明書更新時にパスフレーズファイル保存を確認
=> fix #215(証明書パスフレーズ保存)

pom.xml, src/main/java/org/montsuqi/monsiaj/widgets/NumberEntry.java
* 日レセ2月パッチでNumberEntryウィジェットにtext_max_lengthプロパティが設定された画面定義体が追加された
* text_max_lengthプロパティはEntry.classに適用され、EntryがもつLengthLimitableDocumentオブジェクトにsetLimit()を実行する
* NumberEntryはEntryの子クラスだがDocumentはPlainDocumentベースのNumberDocumentに変更している
* NumberDocumentはsetLimit()を持たないため、text_max_lengthプロパティ適用時にエラーとなる(ウィジェットひょうじされない) 
*  NumberDocumentの親クラスをPlainDocumentからLengthLimitableDocument(PlainDocumentベース)に変更する
* 2月パッチ適用の日レセでtext_max_lengthが指定されたNumberEntryが正常動作することを確認
=> NumberDocumentの親クラスをLengthLimitableDocumentに変更
